
--Admin to BlueBike Database
CREATE USER nagpalm IDENTIFIED BY DMDDuser2#123;
ALTER USER nagpalm DEFAULT TABLESPACE DATA;
ALTER USER nagpalm QUOTA unlimited ON USERS;  

GRANT CREATE SESSION TO nagpalm;
GRANT CONNECT, RESOURCE TO nagpalm;
GRANT CREATE TABLE TO NAGPALM;
GRANT CREATE PROCEDURE TO nagpalm;
GRANT EXECUTE ANY PROCEDURE TO nagpalm;
GRANT CREATE PUBLIC SYNONYM TO nagpalm;
GRANT DROP PUBLIC SYNONYM TO nagpalm;
GRANT CREATE ANY VIEW TO NAGPALM;
GRANT CREATE ANY JOB TO NAGPALM;
commit;

--User of BlueBike Database

CREATE USER nemay IDENTIFIED BY DMDDuser1#123;
ALTER USER nemay DEFAULT TABLESPACE DATA;
ALTER USER nemay QUOTA unlimited ON USERS;  
GRANT CREATE SESSION TO nemay;
GRANT CONNECT, RESOURCE TO nemay;
GRANT EXECUTE ANY PROCEDURE TO nemay;
commit;

--Customer Care of BlueBike Database

CREATE USER dighen IDENTIFIED BY DMDDuser3#123;
ALTER USER dighen DEFAULT TABLESPACE DATA;
ALTER USER dighen QUOTA unlimited ON USERS;  
GRANT CREATE SESSION TO dighen;
GRANT CONNECT, RESOURCE TO dighen;
GRANT EXECUTE ANY PROCEDURE TO dighen;
commit;




