SELECT * FROM CUSTOMER;
SELECT * FROM BIKE;
SELECT * FROM DOCK;
SELECT * FROM RENT;
SELECT * FROM WALLET;

SET SERVEROUTPUT ON;
--TEST CASES
--NULL BIKE
EXECUTE START_RIDE(NULL,'LOIS.WALKER@HOTMAIL.COM');

--WRONG BIKE
EXECUTE START_RIDE(1,'LOIS.WALKER@HOTMAIL.COM');

--WRONG EMAIL
EXECUTE START_RIDE(1008,'LOIS.WALKERHOTMAIL.COM');

--NULL EMAIL
EXECUTE START_RIDE(1000,'');

--BIKE UNAVAILABLE BIKE
EXECUTE START_RIDE(1006,'LOIS.WALKER@HOTMAIL.COM');

--BOOKING SUCCESSFULL
EXECUTE START_RIDE(1007,'PATRICK.BAILEY@HOTMAIL.COM'); 

--TRYING TO BOOK NEW RIDE WHEN ANOTHER RIDE IS NOT FINISHED ---1007 is assigned to patrick
EXECUTE START_RIDE(1007,'CAROL.MURPHY@GMAIL.COM');

--PAST UNPAID TRANSACTIONS
EXECUTE START_RIDE(1009,'LOIS.WALKER@HOTMAIL.COM');



