create or replace PROCEDURE AVAILABLE_BIKES IS
    CURRENT_USER VARCHAR(10);
    EX_INCORRECT_USER EXCEPTION;
BEGIN
    SELECT USER INTO CURRENT_USER FROM DUAL;
    IF (CURRENT_USER <> 'NAGPALM') THEN
        RAISE EX_INCORRECT_USER;
    END IF;
    FOR RECORD IN 
    (SELECT B.BIKE_ID, B.BIKE_MODEL,D.DOCK_NAME,D.CITY,D.STATE,D.ZIP_CODE,D.LATITUDE,D.LONGITUDE
    FROM DOCK D
    LEFT JOIN BIKE B ON D.DOCK_ID = B.DOCK_ID
    WHERE BIKE_STATUS = 'AVAILABLE'
    ORDER BY D.ZIP_CODE)
    LOOP
        DBMS_OUTPUT.PUT_LINE('BIKE ID: '|| RECORD.BIKE_ID||' BIKE MODEL: ' || RECORD.BIKE_MODEL || ' DOCK NAME: ' || RECORD.DOCK_NAME || ' CITY: ' || RECORD.CITY || ' STATE: ' || RECORD.STATE || ' ZIP_CODE: ' || RECORD.ZIP_CODE || ' LATITUDE: ' || RECORD.LATITUDE || ' LONGITUDE: ' || RECORD.LONGITUDE);
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN EX_INCORRECT_USER THEN
        DBMS_OUTPUT.PUT_LINE('YOU CANNOT DO THIS ACTION. PLEASE CONTACT ADMIN');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
    ROLLBACK;
END;
/