create or replace PROCEDURE ADD_BALANCE(EMAIL IN CUSTOMER.EMAIL_ID%TYPE, NEW_BAL IN WALLET.BALANCE%TYPE) AS
    VAL NUMBER;
    W_ID WALLET.WALLET_ID%TYPE;
    BAL WALLET.BALANCE%TYPE;
    DOES_NOT_EXIST EXCEPTION;
    EX_EMAIL_NULL EXCEPTION;
    USER_EXISTS_EXCEP EXCEPTION;
    BAL_NULL EXCEPTION;
BEGIN    
    EXECUTE IMMEDIATE ('SELECT COUNT(*) from (SELECT 1 from dual where REGEXP_LIKE ('''||EMAIL||''', ''^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$''))') INTO VAL;

    IF LENGTH(UPPER(EMAIL)) IS NULL OR VAL<1 THEN
        RAISE EX_EMAIL_NULL;
    END IF;

    IF NEW_BAL IS NULL  OR NEW_BAL<0 THEN
        RAISE BAL_NULL;
    END IF;

    EXECUTE IMMEDIATE ('SELECT COUNT(*) FROM (SELECT WALLET_ID FROM CUSTOMER WHERE EMAIL_ID='''||EMAIL||''')') INTO VAL;

    IF VAL=0 THEN
        RAISE DOES_NOT_EXIST;
    END IF;

    EXECUTE IMMEDIATE ('SELECT WALLET_ID FROM CUSTOMER WHERE EMAIL_ID='''||EMAIL||'''') INTO W_ID;
    EXECUTE IMMEDIATE ('SELECT BALANCE FROM WALLET WHERE WALLET_ID='||W_ID) INTO BAL;

    BAL:= BAL+NEW_BAL;
    EXECUTE IMMEDIATE ('UPDATE WALLET SET BALANCE=' ||BAL|| ' WHERE WALLET_ID = '||W_ID);

    DBMS_OUTPUT.PUT_LINE('BALANCE FOR '||EMAIL||'  IS '||BAL);
    COMMIT;

    EXCEPTION
    WHEN BAL_NULL THEN
        DBMS_OUTPUT.PUT_LINE('INPUT BALANCE VALUE IS NULL OR LESS THAN 0');        
    WHEN EX_EMAIL_NULL THEN
        DBMS_OUTPUT.PUT_LINE('EMAIL FORMAT INCORRECT, TRY AGAIN');    
    WHEN DOES_NOT_EXIST THEN
        DBMS_OUTPUT.PUT_LINE('REGISTER CUSTOMER IN DATABSE');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ENTER VALID INPUTS');    
    ROLLBACK;
END;