create or replace PROCEDURE CURRENT_BALANCE(EMAIL IN CUSTOMER.EMAIL_ID%TYPE, O_BAL OUT WALLET.BALANCE%TYPE) AS
    VAL NUMBER;
    W_ID WALLET.WALLET_ID%TYPE;
    BAL WALLET.BALANCE%TYPE;
    USER_DOESNT_EXIST_EXCEP EXCEPTION;
    EMAIL_ISSUE EXCEPTION;

BEGIN
    EXECUTE IMMEDIATE ('SELECT COUNT(*) from (SELECT 1 from dual where REGEXP_LIKE ('''||EMAIL||''', ''^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$''))') INTO VAL;

    IF LENGTH(UPPER(EMAIL)) IS NULL OR VAL<1 THEN
        RAISE EMAIL_ISSUE;
    END IF;
    
    EXECUTE IMMEDIATE ('SELECT COUNT(*) FROM CUSTOMER WHERE UPPER(EMAIL_ID)=UPPER('''||EMAIL||''')') INTO VAL;

    IF VAL<1 THEN
        RAISE USER_DOESNT_EXIST_EXCEP;
    END IF;

    EXECUTE IMMEDIATE ('SELECT WALLET_ID FROM CUSTOMER WHERE EMAIL_ID='''||EMAIL||'''') INTO W_ID;
    EXECUTE IMMEDIATE ('SELECT BALANCE FROM WALLET WHERE WALLET_ID='||W_ID) INTO BAL;

    DBMS_OUTPUT.PUT_LINE('BALANCE FOR '||EMAIL||' IS '||BAL);
    O_BAL:=BAL;
    COMMIT;

    EXCEPTION
    WHEN EMAIL_ISSUE THEN
        DBMS_OUTPUT.PUT_LINE('EMAIL FORMAT INCORRECT, TRY AGAIN');
    WHEN USER_DOESNT_EXIST_EXCEP THEN
        DBMS_OUTPUT.PUT_LINE('USER DOES NOT EXIST, REGISTER FIRST AS NEW USER');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ENTER VALID INPUTS');    
    ROLLBACK;
END;