create or replace PROCEDURE PRINT_MEMBERSHIP_OPTIONS IS
BEGIN
  DBMS_OUTPUT.PUT_LINE(' ');
  FOR i in (SELECT * FROM MEMBERSHIP ORDER BY MEMBERSHIP_ID) LOOP
    dbms_output.put_line('     ' || i.MEMBERSHIP_ID || ' ' || i.MEMBERSHIP_TYPE || ' ' || i.MEMBERSHIP_AMOUNT);
  END LOOP; 
  DBMS_OUTPUT.PUT_LINE('TO BUY MEMBERSHIP EXECUTE MEMBERSHIP_REGISTER_CHOICE(''REGISTERED_EMAIL'',MEMBERSHIP_ID);');
END;