create or replace TRIGGER SET_CUSTOMERTECHNICIAN_AVAILABLE
  AFTER UPDATE of TICKET_STATUS ON TICKETING_QUEUE 
  FOR EACH ROW
    WHEN (new.TICKET_STATUS = 'CLOSED')
BEGIN
    UPDATE CUSTOMER_TECHNICIAN_STATE 
    SET CUSTOMER_TECHNICIAN_STATUS = 'AVAILABLE' WHERE EMPLOYEE_ID = :old.TICKET_AGENT;
    DBMS_OUTPUT.PUT_LINE('Ticket Closed');

END;
