create or replace TRIGGER SET_CUSTOMERTECHNICIAN_UNAVAILABLE
  AFTER UPDATE of TICKET_STATUS ON TICKETING_QUEUE 
  FOR EACH ROW
    WHEN (new.TICKET_STATUS = 'ASSIGNED')
BEGIN
    UPDATE CUSTOMER_TECHNICIAN_STATE 
    SET CUSTOMER_TECHNICIAN_STATUS = 'UNAVAILABLE' WHERE EMPLOYEE_ID = :old.TICKET_AGENT;
    DBMS_OUTPUT.PUT_LINE('Ticket Assigned');
    
END;
