SET SERVEROUTPUT ON;

--TEST CASES FOR PROCEDURE DELETE_DISCOUNT
--DELETING COUPON_ID 14
EXECUTE DELETE_DISCOUNT(14);

--PASSING A COUPON ID NOT PRESENT IN THE DISCOUNT TABLE
EXECUTE DELETE_DISCOUNT(16);

--PASSING A NULL COUPON ID
EXECUTE DELETE_DISCOUNT( );