set serveroutput on;

-- TEST CASES FOR DELETE_BIKE

SELECT * FROM BIKE;

--TEST CASE 1
--DELETING BIKE 1002 FROM BIKE TABLE
EXECUTE DELETE_BIKE(1002);

--TEST CASE 2 
--INSERTING WRONG BIKEID
EXECUTE DELETE_BIKE(1056);

--TEST CASE 3
--INSERTING NULL VALUE IN BIKE ID
EXECUTE DELETE_BIKE();