SET SERVEROUTPUT ON;


--TEST CASES FOR PROCEDURE CURRENT_BALANCE
-- WHEN PROPER VALUES ARE PASSED AS PARAMETER
DECLARE
VAL WALLET.BALANCE%TYPE;
BEGIN
    CURRENT_BALANCE('BRENDA.ROBINSON@GMAIL.COM',VAL);
    DBMS_OUTPUT.PUT_LINE(VAL);
END;


--WHEN WRONG EMAIL ID IS INPUT AS PASSED AS PARAMETER
DECLARE
VAL WALLET.BALANCE%TYPE;
BEGIN
    CURRENT_BALANCE('BREND.ROBINSON@GMAIL.COM',VAL);
    DBMS_OUTPUT.PUT_LINE(VAL);
END;

--WHEN BLANK EMAIL ID IS THE INPUT
DECLARE
VAL WALLET.BALANCE%TYPE;
BEGIN
    CURRENT_BALANCE('',VAL);
    DBMS_OUTPUT.PUT_LINE(VAL);
END;