-- ADD_DISCOUNT TEST CASES
SET SERVEROUTPUT ON;

--TEST CASE 1
--ADD NEW COUPON
EXECUTE ADD_DISCOUNT('TEST4',18.547);

--TEST CASE 2
--ADD OLD COUPON WITH NEW VALUE
EXECUTE ADD_DISCOUNT('TEST4',11);

--TEST CASE 3
--COUPON EXIST
EXECUTE ADD_DISCOUNT('TEST4',11);

--TEST CASE 3
--NULL COUPON
EXECUTE ADD_DISCOUNT('',11);

--TEST CASE 4
--NULL AMOUNT
EXECUTE ADD_DISCOUNT('T',NULL);