
--TEST CASES FOR PROCEDURE MEMBERSHIP REGISTER CHOICE

SET SERVEROUTPUT ON;

--TEST CASE 1
--PASSING A NEW MEMBERSHIP ID FOR A CUSTOMER WITH AN EXISTING MEMBERSHIP ID
EXECUTE MEMBERSHIP_REGISTER_CHOICE('DIANE.EVANS@YAHOO.COM',3);

--TEST CASE 2
--ENTERING AN INVALID EMAIL ID
EXECUTE MEMBERSHIP_REGISTER_CHOICE('RACHEL.EVANS@YAHOO.COM',3);

--TEST CASE 3 
--ENTERING AN INVALID MEMBERSHIP ID
EXECUTE MEMBERSHIP_REGISTER_CHOICE('walter.white@gmail.com',5);

--TEST CASE 4
--adding a new membership ID to the user but with insufficient balance to purchase that membership
EXECUTE MEMBERSHIP_REGISTER_CHOICE('walter.white@gmail.com',1);

