--CUSTOMER
EXECUTE DELETE_SEQUENCE_USER('CUSTOMER','USER');
CREATE USER CUSTOMER IDENTIFIED BY "DMDDuser5#123";

GRANT CREATE SESSION TO CUSTOMER;

GRANT EXECUTE ON CUSTOMER_ACTIONS to CUSTOMER;

CREATE OR REPLACE PUBLIC SYNONYM CUSTOMER_ACTIONS for NAGPALM.CUSTOMER_ACTIONS;

GRANT EXECUTE ON AVAILABLE_BIKES to CUSTOMER;

--MANAGER
EXECUTE DELETE_SEQUENCE_USER('MNGR','USER');
CREATE USER MNGR IDENTIFIED BY "DMDDuser6#123";

GRANT CREATE SESSION TO MNGR;

GRANT EXECUTE ON MANAGER_ACTIONS to MNGR;

CREATE OR REPLACE PUBLIC SYNONYM MANAGER_ACTIONS for NAGPALM.MANAGER_ACTIONS;

GRANT EXECUTE ON AVAILABLE_BIKES to MNGR;

--CUSTOMER CARE
EXECUTE DELETE_SEQUENCE_USER('CTECH','USER');
CREATE USER CTECH IDENTIFIED BY "DMDDuser7#123";

GRANT CREATE SESSION TO CTECH;

GRANT EXECUTE ON CUSTOMER_CARE_ACTIONS to CTECH;

CREATE OR REPLACE PUBLIC SYNONYM CUSTOMER_CARE_ACTIONS for NAGPALM.CUSTOMER_CARE_ACTIONS;

GRANT EXECUTE ON AVAILABLE_BIKES to CTECH;

